### ISSUE TITLE
调用mcp工具有时候会报错：ValueError: <string>:1 Unexpected end of input at column

### ISSUE THREAD

**Issue by Kun-Zhang-x** [QwenLM/Qwen-Agent#547]
![Image](https://github.com/user-attachments/assets/b8a661ce-5012-4118-971f-ccf44c616b99)

[TOOL_CALL] quickchart-server-generate_chart
Traceback (most recent call last):
  File "/app/chatbi-agent/assistant_qwen3.py", line 116, in orderOfRecord
    result = run_bi(query, request.model, request.api_key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/chatbi-agent/assistant_qwen3.py", line 79, in run_bi
    for response in bot.run(messages=messages, stream=False, lang='zh'):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/qwen_agent/agent.py", line 110, in run
    for rsp in self._run(messages=new_messages, **kwargs):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/qwen_agent/agents/fncall_agent.py", line 73, in _run
    for output in output_stream:
                  ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/qwen_agent/llm/base.py", line 370, in _convert_messages_iterator_to_target_type
    for messages in messages_iter:
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/qwen_agent/llm/base.py", line 249, in _format_and_cache
    for o in output:
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/qwen_agent/llm/base.py", line 355, in _postprocess_messages_iterator
    yield self._postprocess_messages(pre_msg, fncall_mode=fncall_mode, generate_cfg=generate_cfg)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/qwen_agent/llm/function_calling.py", line 59, in _postprocess_messages
    messages = self.fncall_prompt.postprocess_fncall_messages(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/qwen_agent/llm/fncall_prompts/nous_fncall_prompt.py", line 188, in postprocess_fncall_messages
    fn = json5.loads(one_tool_call_txt[0].strip())
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/json5/lib.py", line 205, in loads
    raise ValueError(err)
ValueError: <string>:1 Unexpected end of input at column 708
{"type": "doughnut", "labels": ["案件大类_10", "案件大类_6", "案件大类_8", "案件大类_7", "案件大类_3", "案件大类_9", "案件大类_5", "案件大类_4", "案件大类_1", "案件大类_2"], "datasets": [{"label": "案件数量", "data": [12, 7, 14, 11, 14, 16, 6, 10, 5, 5], "backgroundColor": ["#FF6384", "#36A2EB", "#FFCE56", "#4BC0C0", "#9966FF", "#FF9F40", "#FF6384", "#36A2EB", "#FFCE56", "#4BC0C0"], "borderColor": ["#FF6384", "#36A2EB", "#FFCE56", "#4BC0C0", "#9966FF", "#FF9F40", "#FF6384", "#36A2EB", "#FFCE56", "#4BC0C0"]}], "title": "案件类型分布", "options": {"responsive": true, "plugins": {"doughnutlabel": {"labels": [{"text": "总数: 100", "font": {"size": 20}}, {"text": "单位：件", "font": {"size":

**Comment by tuhahaha** [comment]
您好，这看起来是tool参数输出不是合法json了，请问您用的是：1: 什么模型， 2: 如何部署的, 3: llm_cfg是如何设置的？

**Comment by Kun-Zhang-x** [comment]
> 您好，这个看起来是工具参数输出不合法的json了，请问您用的是：1: 什么模型，2: 如何配置的，3: llm_cfg 是如何设置的？

**以下是我的demo，模型采用是阿里百炼的qwen3-32b**

```
def init_agent_service(model: str, api_key: str):
    llm_cfg = {
        'model': 'qwen3-32b',
        'model_server': 'https://dashscope.aliyuncs.com/compatible-mode/v1',
        'api_key': api_key,

        'generate_cfg': {
            'temperature': 0,
            'extra_body': {
                'chat_template_kwargs': {'enable_thinking': True}
            },
            'thought_in_content': False
        },
    }
    tools = [
        {
            'mcpServers': {
                "operateMysql": {
                    "isActive": "true",
                    "name": "operateMysql",
                    "command": "uv",
                    "args": [
                        "--directory",
                        "E:\\model\\owl\\mysql_mcp_server_pro\\src",
                        "run",
                        "server.py",
                        "--stdio"
                    ],
                    "env": {
                        "MYSQL_HOST": "localhost",
                        "MYSQL_PORT": "3306",
                        "MYSQL_USER": "root",
                        "MYSQL_PASSWORD": "root",
                        "MYSQL_DATABASE": "scb1",
                        "MYSQL_ROLE": "admin"
                    }
                },
                "quickchart-server": {
                    "command": "node",
                    "args": ["E:\\model\\owl\\Quickchart-MCP-Server\\build\\index.js"]
                }
            }
        }
    ]
    system_message = """
    你是一个数据库分析专家系统，擅长根据用户需求设计SQL查询并生成可视化图表。你的任务是：
    1. 理解用户提供的自然语言需求；
    2. 按照指定操作流程，调用工具完成数据库字段分析、数据查询和图表生成；
    3. 严格遵守约束条件，避免任何未经验证的推断。
    """
    bot = Assistant(llm=llm_cfg,
                    function_list=tools,
                    name='Qwen Tool-calling',
                    system_message=system_message)

    return bot


bot = init_agent_service(model, api_key)

def run_bi(query: str):

    messages = [{'role': 'user', 'content': query}]
    response_plain_text = ''
    for response in bot.run(messages=messages, stream=False, lang='zh'):
        response_plain_text = typewriter_print(response, response_plain_text)

    return response_plain_text

```

也试过vllm在本地部署的qwen3-32b，但也会出现这种问题，docker-compose如下
```
version: '3'
services:
  vllm:
    container_name: qwen3
    restart: always
    image: vllm/vllm-openai:v0.8.5
    ipc: host
    volumes:
      - /data/soft/Qwen3-32B:/models/Qwen3-32B
    command: ["--model", "/models/Qwen3-32B", "--served-model-name", "Qwen/Qwen3-32B", "--max-model-len", "29999", "--max-num-seqs", "32", "--gpu-memory-utilization", "0.90", "--tensor-parallel-size", "2", "--pipeline-parallel-size", "3", "--kv-cache-dtype", "auto", "--trust-remote-code", "--enable-auto-tool-choice", "--tool-call-parser", "hermes","--enable-reasoning","--reasoning-parser","deepseek_r1"]
    ports:
      - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
```
